apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: reservation-app
data:
  rules.yml: |
    groups:
    - name: reservation-app.rules
      rules:
      # Recording rules
      - record: app:rps:rate1m
        expr: sum(rate(http_request_duration_seconds_count[1m]))
      # Error ratio (5xx / all). clamp_min keeps denom >=1 so we get 0 instead of NaN when idle.
      - record: app:errors_ratio:5m
        expr: |
          sum(rate(http_request_duration_seconds_count{namespace="reservation-app",service="reservation-app",status_code=~"5.."}[5m]))
          /
          clamp_min(sum(rate(http_request_duration_seconds_count{namespace="reservation-app",service="reservation-app"}[5m])), 1)

      # Availability percentage (SLO-style)
      - record: app:availability_pct:5m
        expr: 100 * (1 - app:errors_ratio:5m)

      # Latency p95 over 5m
      - record: app:latency_p95:5m
        expr: |
          histogram_quantile(
            0.95,
            sum(rate(http_request_duration_seconds_bucket{namespace="reservation-app",service="reservation-app"}[5m]))
            by (le)
          )
      # Alerts
      - alert: AppDown
        expr: sum(up) == 0
        for: 1m
        labels: { severity: critical }
        annotations:
          summary: "App is down"
      - alert: HighErrorRate
        expr: app:errors_ratio:5m > 0.05
        for: 5m
        labels: { severity: warning }
        annotations:
          summary: "5xx ratio > 5% (5m)"
      - alert: HighLatencyP95
        expr: app:latency_p95:5m > 0.5
        for: 5m
        labels: { severity: warning }
        annotations:
          summary: "p95 latency > 500 ms (5m)"
      - alert: HighMemory
        expr: process_resident_memory_bytes > 3e8
        for: 10m
        labels: { severity: warning }
        annotations:
          summary: "RSS memory > 300MB (10m)"
      - alert: EventLoopLagHigh
        expr: nodejs_eventloop_lag_seconds > 0.1
        for: 5m
        labels: { severity: warning }
        annotations:
          summary: "Node event loop lag > 100ms (5m)"
